#!/usr/bin/env python3
"""
Reviewer Agent
==============
Triggered on every PR open/update. Performs an AI-powered code review
covering quality, architecture, correctness, and maintainability.

Returns one of:
  - APPROVE          — code is good to merge
  - REQUEST_CHANGES  — specific issues must be fixed
  - COMMENT          — observations only, no blocking action

A REQUEST_CHANGES verdict feeds back into the Developer Agent fix loop.
"""

import os
import json
import sys
import re
from pathlib import Path

from github import Github, GithubException
from openai import OpenAI

# ── Configuration ─────────────────────────────────────────────────────────────
GITHUB_TOKEN   = os.environ["GITHUB_TOKEN"]
AI_API_KEY     = os.environ["AI_API_KEY"]
AI_MODEL       = os.environ.get("AI_MODEL", "gpt-4o")
AI_BASE_URL    = os.environ.get("AI_BASE_URL", "https://api.openai.com/v1")
AI_MAX_TOKENS  = int(os.environ.get("AI_MAX_TOKENS", "4096"))
PR_NUMBER      = int(os.environ["PR_NUMBER"])
REPO_FULL_NAME = os.environ["REPO_FULL_NAME"]

# ── Clients ───────────────────────────────────────────────────────────────────
g    = Github(GITHUB_TOKEN)
repo = g.get_repo(REPO_FULL_NAME)
ai   = OpenAI(api_key=AI_API_KEY, base_url=AI_BASE_URL)


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_prompt(name: str) -> str:
    path = Path(f"prompts/{name}.prompt.md")
    return path.read_text(encoding="utf-8") if path.exists() else ""


def call_ai(system_prompt: str, user_message: str) -> str:
    response = ai.chat.completions.create(
        model=AI_MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_message},
        ],
        max_tokens=AI_MAX_TOKENS,
        temperature=0.1,
    )
    return response.choices[0].message.content


def extract_json(text: str) -> dict:
    match = re.search(r"```(?:json)?\s*([\s\S]+?)\s*```", text)
    if match:
        return json.loads(match.group(1))
    return json.loads(text.strip())


def build_diff_summary(pr) -> tuple[str, int]:
    """Build a readable diff summary; return (text, file_count)."""
    files = list(pr.get_files())
    sections: list[str] = []

    for f in files[:20]:  # Cap at 20 files to stay within token budget
        patch = f.patch or "(binary or empty)"
        sections.append(
            f"### `{f.filename}` — {f.status}  (+{f.additions} / -{f.deletions})\n"
            f"```diff\n{patch[:3000]}\n```"
        )

    if len(files) > 20:
        sections.append(f"\n_… {len(files) - 20} more files not shown_")

    return "\n\n".join(sections), len(files)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    pr = repo.get_pull(PR_NUMBER)
    print(f"🔍 Reviewer Agent — PR #{PR_NUMBER}: {pr.title}")

    diff_text, file_count = build_diff_summary(pr)

    # Fetch linked issue description for context
    linked_issue_text = ""
    if pr.body:
        m = re.search(r"(?:Resolves|Closes|Fixes)\s+#(\d+)", pr.body, re.IGNORECASE)
        if m:
            try:
                issue = repo.get_issue(int(m.group(1)))
                linked_issue_text = f"**Linked issue #{issue.number}:** {issue.title}\n\n{(issue.body or '')[:1000]}"
            except GithubException:
                pass

    system_prompt = load_prompt("reviewer")
    user_message  = f"""## Pull Request

**PR #{PR_NUMBER}:** {pr.title}
**Author:** @{pr.user.login}
**Files changed:** {file_count}

## PR Description
{(pr.body or '(none)')[:2000]}

{linked_issue_text}

## Diff
{diff_text}
"""

    print("🤖 Calling AI reviewer…")
    raw = call_ai(system_prompt, user_message)

    try:
        review = extract_json(raw)
    except (json.JSONDecodeError, ValueError):
        # Degrade gracefully — post as comment
        review = {
            "verdict":     "COMMENT",
            "summary":     raw,
            "issues":      [],
            "suggestions": [],
        }

    verdict     = str(review.get("verdict", "COMMENT")).upper()
    summary     = review.get("summary", "")
    issues      = review.get("issues",      [])
    suggestions = review.get("suggestions", [])

    # Normalise verdict to one of the three accepted GitHub review events
    if verdict not in ("APPROVE", "REQUEST_CHANGES", "COMMENT"):
        verdict = "COMMENT"

    verdict_badge = {
        "APPROVE":         "✅ APPROVED",
        "REQUEST_CHANGES": "🔄 CHANGES REQUESTED",
        "COMMENT":         "💬 COMMENT",
    }[verdict]

    issues_md      = "\n".join(f"- ❌ {i}" for i in issues)      or "_None_"
    suggestions_md = "\n".join(f"- 💡 {s}" for s in suggestions) or "_None_"

    review_body = f"""## 🔍 AI Code Review — {verdict_badge}

### Summary
{summary}

### Issues Found
{issues_md}

### Suggestions
{suggestions_md}

---
*🤖 Generated by Reviewer Agent · model: {AI_MODEL}*
"""

    # Submit the review via the GitHub Reviews API
    try:
        pr.create_review(body=review_body, event=verdict)
        print(f"  ✅ Review submitted: {verdict}")
    except GithubException as exc:
        # Fallback: post as a regular comment (e.g. author reviewing own PR)
        print(f"  ⚠️  create_review failed ({exc}), falling back to comment")
        pr.create_issue_comment(review_body)


if __name__ == "__main__":
    main()
